In [0]:
import pandas as pd

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

#Dataset is uploaded to moodle

In [0]:
print(pd.__version__)

0.24.2

In [0]:
from google.colab import files
file=files.upload()

Saving vehicles_data.csv to vehicles_data.csv

In [0]:

!ls

random_people.csv  sample_data	vehicles_data.csv

#Read CSV File using Pandas and display first 5 items

In [0]:
df = pd.read_csv("vehicles_data.csv")

df.head(5)

   co2TailpipeGpm  comb08  cylinders  ...            trany           VClass  year
0      423.190476      21        4.0  ...     Manual 5-spd      Two Seaters  1985
1      807.909091      11       12.0  ...     Manual 5-spd      Two Seaters  1985
2      329.148148      27        4.0  ...     Manual 5-spd  Subcompact Cars  1985
3      807.909091      11        8.0  ...  Automatic 3-spd             Vans  1985
4      467.736842      19        4.0  ...     Manual 5-spd     Compact Cars  1993

[5 rows x 14 columns]

#Display last 5 items

In [0]:
df.tail(5)

       comb08  cylinders  displ  ...        VClass  year economical
41849      22        4.0    2.2  ...  Compact Cars  1993        Yes
41850      23        4.0    2.2  ...  Compact Cars  1993        Yes
41851      21        4.0    2.2  ...  Compact Cars  1993        Yes
41852      21        4.0    2.2  ...  Compact Cars  1993        Yes
41853      18        4.0    2.2  ...  Compact Cars  1993         No

[5 rows x 14 columns]

#Display Random 5 items

In [0]:
df.sample(5)

       comb08  cylinders  ...  year economical
23724      18        6.0  ...  1985         No
31039      27        4.0  ...  2017        Yes
38021      18        6.0  ...  1990         No
23599      25        4.0  ...  2012        Yes
29353      25        6.0  ...  2016        Yes

[5 rows x 14 columns]

#Display defined rows and columns

In [0]:
print(df.iloc[0:5, 0:5])

   comb08  cylinders  displ                       drive  fuelCost08
0      21        4.0    2.0            Rear-Wheel Drive        1900
1      11       12.0    4.9            Rear-Wheel Drive        3600
2      27        4.0    2.2           Front-Wheel Drive        1450
3      11        8.0    5.2            Rear-Wheel Drive        3600
4      19        4.0    2.2  4-Wheel or All-Wheel Drive        2600

#Display specific attributes from the data

In [0]:
df[['make', 'model','year']].head()

         make                model  year
0  Alfa Romeo   Spider Veloce 2000  1985
1     Ferrari           Testarossa  1985
2       Dodge              Charger  1985
3       Dodge  B150/B250 Wagon 2WD  1985
4      Subaru     Legacy AWD Turbo  1993

In [0]:
df.shape

(41854, 14)

#Statistical data

In [0]:
df.describe()

       co2TailpipeGpm        comb08  ...     highway08          year
count    41854.000000  41854.000000  ...  41854.000000  41854.000000
mean       465.250402     20.670951  ...     24.561619   2001.848163
std        123.669696      7.730059  ...      7.767764     11.301379
min          0.000000      7.000000  ...      9.000000   1984.000000
25%        386.391304     17.000000  ...     20.000000   1991.000000
50%        444.350000     20.000000  ...     24.000000   2003.000000
75%        522.764706     23.000000  ...     28.000000   2012.000000
max       1269.571429    136.000000  ...    124.000000   2020.000000

[8 rows x 7 columns]

In [0]:
df.median()

comb08          20.0
cylinders        6.0
displ            3.0
fuelCost08    2200.0
highway08       24.0
year          2003.0
dtype: float64

In [0]:
df.comb08.min()

7

In [0]:
df.comb08.max()

136

In [0]:
df.comb08.sum()

865162

#Display the datatype for each attribute

In [0]:
df.dtypes

co2TailpipeGpm    float64
comb08              int64
cylinders         float64
displ             float64
drive              object
fuelCost08          int64
fuelType           object
highway08           int64
make               object
model              object
mpgData            object
trany              object
VClass             object
year                int64
dtype: object

In [0]:
df.groupby('make').mean().fuelCost08.head()

make
AM General                     2725.000000
ASC Incorporated               3100.000000
Acura                          2229.718310
Alfa Romeo                     2245.652174
American Motors Corporation    2242.592593
Name: fuelCost08, dtype: float64

In [0]:
df.sort_values('fuelCost08').iloc[0:7, 0:10]

       comb08  cylinders  displ  ...     make                        model mpgData
32815     130        NaN    NaN  ...    Tesla           Model 3 Long Range       Y
34560     131        NaN    NaN  ...    Tesla       Model 3 Standard Range       N
34561     133        NaN    NaN  ...    Tesla  Model 3 Standard Range Plus       N
33423     136        NaN    NaN  ...  Hyundai               Ioniq Electric       N
32599     136        NaN    NaN  ...  Hyundai               Ioniq Electric       N
32740     126        NaN    NaN  ...    Tesla           Model 3 Long Range       N
31256     136        NaN    NaN  ...  Hyundai               Ioniq Electric       N

[7 rows x 10 columns]

In [0]:
df.sort_values(by = ['fuelCost08', 'make']).iloc[0:7, 0:10]

       comb08  cylinders  displ  ...     make                   model mpgData
31256     136        NaN    NaN  ...  Hyundai          Ioniq Electric       N
32599     136        NaN    NaN  ...  Hyundai          Ioniq Electric       N
33423     136        NaN    NaN  ...  Hyundai          Ioniq Electric       N
32740     126        NaN    NaN  ...    Tesla      Model 3 Long Range       N
32815     130        NaN    NaN  ...    Tesla      Model 3 Long Range       Y
34312     130        NaN    NaN  ...    Tesla      Model 3 Long Range       N
34560     131        NaN    NaN  ...    Tesla  Model 3 Standard Range       N

[7 rows x 10 columns]

In [0]:
#reset_index(drop= True)
df.sort_values(by = ['fuelCost08', 'make']).iloc[0:7, 0:10].reset_index()

   index  comb08  cylinders  ...     make                   model  mpgData
0  31256     136        NaN  ...  Hyundai          Ioniq Electric        N
1  32599     136        NaN  ...  Hyundai          Ioniq Electric        N
2  33423     136        NaN  ...  Hyundai          Ioniq Electric        N
3  32740     126        NaN  ...    Tesla      Model 3 Long Range        N
4  32815     130        NaN  ...    Tesla      Model 3 Long Range        Y
5  34312     130        NaN  ...    Tesla      Model 3 Long Range        N
6  34560     131        NaN  ...    Tesla  Model 3 Standard Range        N

[7 rows x 11 columns]

In [0]:
np.random.seed(8)
def cost(x):
    if x >= 8:
        return np.random.randint(60000, 200000)
    
    else:
        return np.random.randint(20000, 50000)

df['model_cost'] = df.cylinders.apply(cost)
df.head(5)

   comb08  cylinders  displ  ... economical  randNumCol model_cost
0      21        4.0    2.0  ...        Yes      114934      24547
1      11       12.0    4.9  ...         No      179710      85940
2      27        4.0    2.2  ...        Yes       20174      38417
3      11        8.0    5.2  ...         No       81979     122426
4      19        4.0    2.2  ...         No       52881      30376

[5 rows x 16 columns]

In [0]:
costly_cars=df[df["model_cost"]>=60000]
costly_cars.sort_values('model_cost').head(10)

       comb08  cylinders  displ  ... economical  randNumCol model_cost
15587      10       12.0    6.5  ...         No      106106      60016
7168       19        8.0    3.5  ...         No      115812      60025
24112      14        8.0    6.2  ...         No      169655      60042
9960       14        8.0    5.2  ...         No       87705      60063
10951      13       12.0    5.5  ...         No      195614      60065
8115       12        8.0    5.2  ...         No      116862      60073
18008      11        8.0    5.9  ...         No      102925      60078
23622      17        8.0    5.3  ...         No       80007      60091
4254       15        8.0    5.7  ...         No      131158      60103
38699      12        8.0    5.2  ...         No       29115      60105

[10 rows x 16 columns]

#Data filter based on attribute

In [0]:
filtered_data = df[df["make"]=='Ferrari']
filtered_data.head(5)

     comb08  cylinders  displ  ... economical  randNumCol model_cost
1        11       12.0    4.9  ...         No      179710      85940
700      14        8.0    3.4  ...         No      132367     192909
701      13        8.0    3.4  ...         No      160548     131152
703      11       12.0    4.9  ...         No       22133     118988
809      13        8.0    3.4  ...         No       98705     110259

[5 rows x 16 columns]

#Drop an attribute

In [0]:
df.drop('co2TailpipeGpm',1,inplace=True)
print(df[0:5])

KeyError: ignored

#Crete a new dataframe using concatenate

In [0]:
data_make = df['make']
data_model = df['model']
data_year = df['year']
data_displ=df['displ']
data_cost=df['model_cost']

new_data = pd.concat([data_make, data_model, data_year, data_displ, data_cost], axis=1)
new_data.head(5)
#display(new_data[0:5])

         make                model  year  displ  model_cost
0  Alfa Romeo   Spider Veloce 2000  1985    2.0       24547
1     Ferrari           Testarossa  1985    4.9       85940
2       Dodge              Charger  1985    2.2       38417
3       Dodge  B150/B250 Wagon 2WD  1985    5.2      122426
4      Subaru     Legacy AWD Turbo  1993    2.2       30376

In [0]:
new_data.values

array([['Alfa Romeo', 'Spider Veloce 2000', 1985, 2.0, 24547],
       ['Ferrari', 'Testarossa', 1985, 4.9, 85940],
       ['Dodge', 'Charger', 1985, 2.2, 38417],
       ...,
       ['Subaru', 'Legacy AWD', 1993, 2.2, 29933],
       ['Subaru', 'Legacy AWD', 1993, 2.2, 31340],
       ['Subaru', 'Legacy AWD Turbo', 1993, 2.2, 37572]], dtype=object)

In [0]:
new_data[['year']].values

array([[1985],
       [1985],
       [1985],
       ...,
       [1993],
       [1993],
       [1993]])

#Adding a new attribute based on results from exisiting attribute

In [0]:
def economy(x):
    if x >= 20:
        return 'Yes'
    else:
        return 'No'

df['economical'] = df.comb08.apply(economy)
df.head(5)

#df.economical.value_counts()

   comb08  cylinders  displ  ...           VClass  year economical
0      21        4.0    2.0  ...      Two Seaters  1985        Yes
1      11       12.0    4.9  ...      Two Seaters  1985         No
2      27        4.0    2.2  ...  Subcompact Cars  1985        Yes
3      11        8.0    5.2  ...             Vans  1985         No
4      19        4.0    2.2  ...     Compact Cars  1993         No

[5 rows x 14 columns]

In [0]:
df_high = df[df["comb08"]>=20]

In [0]:


# Importing pandas as pd 
import pandas as pd 
  
# Creating the first Dataframe using dictionary 
f1 = pd.DataFrame({"a":[1, 2, 3, 4], 
                    "b":[5, 6, 7, 8]}) 
  
# Creating the Second Dataframe using dictionary 
f2 = pd.DataFrame({"a":[1, 2, 3], 
                    "b":[5, 6, 7],  
                    "c":[1, 5, 4]}) 
  
# for appending df2 at the end of df1 
f1.append(f2, ignore_index = True)

   a  b    c
0  1  5  NaN
1  2  6  NaN
2  3  7  NaN
3  4  8  NaN
4  1  5  1.0
5  2  6  5.0
6  3  7  4.0